language: go
sudo: false
go:
 - 1.8.x
 - 1.9.x
 - 1.10.x
 - 1.11.x

before_install:
  - go get golang.org/x/net/html/charset
  - go get github.com/mattn/goveralls
  - go get github.com/matryer/is
  - go get github.com/spf13/pflag

script:
  - $HOME/gopath/bin/goveralls -service=travis-ci